/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemovalServiceRouteImport } from './routes/removal-service'
import { Route as BookAndPayRouteImport } from './routes/book-and-pay'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RemovalServiceRoute = RemovalServiceRouteImport.update({
  id: '/removal-service',
  path: '/removal-service',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAndPayRoute = BookAndPayRouteImport.update({
  id: '/book-and-pay',
  path: '/book-and-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-and-pay': typeof BookAndPayRoute
  '/removal-service': typeof RemovalServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-and-pay': typeof BookAndPayRoute
  '/removal-service': typeof RemovalServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-and-pay': typeof BookAndPayRoute
  '/removal-service': typeof RemovalServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/book-and-pay' | '/removal-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/book-and-pay' | '/removal-service'
  id: '__root__' | '/' | '/about' | '/book-and-pay' | '/removal-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookAndPayRoute: typeof BookAndPayRoute
  RemovalServiceRoute: typeof RemovalServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/removal-service': {
      id: '/removal-service'
      path: '/removal-service'
      fullPath: '/removal-service'
      preLoaderRoute: typeof RemovalServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-and-pay': {
      id: '/book-and-pay'
      path: '/book-and-pay'
      fullPath: '/book-and-pay'
      preLoaderRoute: typeof BookAndPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookAndPayRoute: BookAndPayRoute,
  RemovalServiceRoute: RemovalServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
